/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pacijent;

import kontroler.Kontroler;
import domen.Laborant;

import domen.Pacijent;
import gui.ModForme;
import gui.PretragaForma;
import gui.termin.RezultatForma;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Milica
 */
public class PacijentForma extends javax.swing.JDialog {

    ModForme mod;

    /**
     * Creates new form Frmpacijent
     */
    public PacijentForma(java.awt.Dialog parent, boolean modal, ModForme mod) {
        super(parent, modal);
        initComponents();
        napuniKomboLaboranti();
        srediFormu(mod);
        setLocationRelativeTo(null);
        this.mod = mod;
        System.out.println(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbLaboranti = new javax.swing.JComboBox<>();
        btnSacuvajPacijenta = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unesite podatke o pacijentu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ime pacijenta: *");

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDatum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDatum.setToolTipText("");

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Prezime pacijenta: *");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kontakt telefon: *");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("e-mail:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Datum rodjenja:  (dd.mm.gggg.) *");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Test koji želi da radi:");

        cbLaboranti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLaboranti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLaboranti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaborantiActionPerformed(evt);
            }
        });

        btnSacuvajPacijenta.setBackground(new java.awt.Color(204, 204, 204));
        btnSacuvajPacijenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacuvajPacijenta.setText("Sačuvaj pacijenta");
        btnSacuvajPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajpacijentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(129, 129, 129)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefon)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSacuvajPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(112, 112, 112)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                        .addComponent(txtIme)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbLaboranti, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbLaboranti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSacuvajPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        txtDatum.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajpacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajpacijentaActionPerformed
        try {
            if (txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty() || txtDatum.getText().isEmpty() || txtTelefon.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja oznacena sa *.");
                return;
            }
            String ime = txtIme.getText().trim();
            String prezime = txtPrezime.getText().trim();
            Date datumR = null;
            try {
                datumR = Kontroler.getInstance().getSdf().parse(txtDatum.getText().trim());
                lblError.setText("");
            } catch (ParseException ex) {
                Logger.getLogger(PacijentForma.class.getName()).log(Level.SEVERE, null, ex);
                lblError.setForeground(Color.red);
                lblError.setText("Unesite datum u formatu dd.mm.gggg.");
                return;
            }
            String telefon = txtTelefon.getText().trim();
            String email = txtEmail.getText().trim();
            Laborant l = (Laborant) cbLaboranti.getSelectedItem();
            
            if (mod == ModForme.UNOS) {
                System.out.println("pre");
                Pacijent pacijent = new Pacijent(Long.MIN_VALUE, ime, prezime, datumR, telefon, email);
                
                pacijent.setLaborant(l);
                
                Kontroler.getInstance().sacuvajPacijenta(pacijent);
                System.out.println("posle");
                int option = JOptionPane.showConfirmDialog(this, "Pacijent je uspesno sačuvan. Da li zelite da unesete još nekog pacijenta?", "", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    txtIme.setText("");
                    txtPrezime.setText("");
                    txtDatum.setText("");
                    txtTelefon.setText("");
                    txtEmail.setText("");
                } else {
                    this.dispose();
                }
                return;
            }
            if (mod == ModForme.IZMENA) {
                Pacijent pac = (Pacijent) session.Session.getInstance().getUseCaseParams().get("izabranipacijent");

                Pacijent p1 = new Pacijent(pac.getPacijentID(), ime, prezime, datumR, telefon, email);
                p1.setLaborant(l);

                Kontroler.getInstance().azurirajPacijenta(p1);
                JOptionPane.showMessageDialog(this, "Pacijent je ušpesno izmenjen.");
                PretragaForma parent = (PretragaForma) getParent();
                parent.osveziTabelu();
            }

        } catch (Exception ex) {
            Logger.getLogger(PacijentForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajpacijentaActionPerformed

    private void cbLaborantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaborantiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLaborantiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajPacijenta;
    private javax.swing.JComboBox<Object> cbLaboranti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void napuniKomboLaboranti() {
        cbLaboranti.removeAllItems();
        try {
            List<Laborant> list = Kontroler.getInstance().dajSveLaborante();
            for (Laborant l : list) {
                cbLaboranti.addItem(l);
            }
        } catch (Exception ex) {
            Logger.getLogger(RezultatForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediFormu(ModForme mod) {

        switch (mod) {
            case UNOS:
                txtIme.setEnabled(true);
                txtPrezime.setEnabled(true);
                txtDatum.setEnabled(true);
                txtEmail.setEnabled(true);
                txtTelefon.setEnabled(true);
                cbLaboranti.setEnabled(true);
                btnSacuvajPacijenta.setVisible(true);
                setTitle("Dodavanje novog pacijenta");
                txtDatum.setForeground(Color.GRAY);
                txtDatum.setText("Na primer 28.10.1996");
                txtDatum.addFocusListener(new FocusListener() {
                    @Override
                    public void focusGained(FocusEvent e) {
                        if (txtDatum.getText().equals("Na primer 28.10.1996")) {
                            txtDatum.setText("");
                            txtDatum.setForeground(Color.BLACK);
                        }
                    }

                    @Override
                    public void focusLost(FocusEvent e) {
                        if (txtDatum.getText().isEmpty()) {
                            txtDatum.setForeground(Color.GRAY);
                            txtDatum.setText("Na primer 28.10.1996");
                        }
                    }
                });

                break;
            case IZMENA:
                txtIme.setEnabled(true);
                txtPrezime.setEnabled(true);
                txtDatum.setEnabled(true);
                txtEmail.setEnabled(true);
                txtTelefon.setEnabled(true);
                cbLaboranti.setEnabled(true);
                btnSacuvajPacijenta.setVisible(true);
                setTitle("Izmena pacijenta");
                for (Object k : session.Session.getInstance().getUseCaseParams().keySet()) {
                    System.out.println(k.toString());
                }
                
                Pacijent p = (Pacijent) session.Session.getInstance().getUseCaseParams().get("izabranipacijent");
                txtIme.setText(p.getIme());
                txtPrezime.setText(p.getPrezime());
                txtDatum.setText(Kontroler.getInstance().getSdf().format(p.getDatumRodjenja()));
                txtTelefon.setText(p.getTelefon());
                txtEmail.setText(p.getEmail());
                cbLaboranti.setSelectedItem(p.getLaborant());
                break;
            case PRIKAZ:
                Pacijent p1 = (Pacijent) session.Session.getInstance().getUseCaseParams().get("izabranipacijent");
                txtIme.setText(p1.getIme());
                txtPrezime.setText(p1.getPrezime());
                txtDatum.setText(Kontroler.getInstance().getSdf().format(p1.getDatumRodjenja()));
                txtTelefon.setText(p1.getTelefon());
                txtEmail.setText(p1.getEmail());
                cbLaboranti.setSelectedItem(p1.getLaborant());
                txtIme.setEnabled(false);
                txtPrezime.setEnabled(false);
                txtDatum.setEnabled(false);
                txtEmail.setEnabled(false);
                txtTelefon.setEnabled(false);
                cbLaboranti.setEnabled(false);
                btnSacuvajPacijenta.setVisible(false);
                setTitle("Prikaz pacijenta");

                break;
        }
    }
}
