/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.laborant;

import kontroler.Kontroler;
import domen.Laborant;
import domen.Test;
import gui.ModForme;
import gui.PretragaForma;
import gui.termin.RezultatForma;
import java.awt.Color;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Milica
 */
public class LaborantForma extends javax.swing.JDialog {

    ModForme mod;

    /**
     * Creates new form FrmCourse
     */
    public LaborantForma(java.awt.Dialog parent, boolean modal, ModForme mod) {
        super(parent, modal);
        initComponents();
        napuniKomboTestova();
        srediFormu(mod);
        setTitle("Dodavanje novog laboranta");
        setLocationRelativeTo(null);
        this.mod = mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLaborant = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblBrojDosijea = new javax.swing.JLabel();
        lblBrojOrdinacije = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrojDosijea = new javax.swing.JTextField();
        txtBrojOrdinacije = new javax.swing.JTextField();
        cbTest = new javax.swing.JComboBox<>();
        btnSacuvajLaboranta = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlLaborant.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaborant.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unesite podatke o laborantu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        lblIme.setBackground(new java.awt.Color(255, 255, 255));
        lblIme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIme.setText("Ime laboranta:*");

        lblPrezime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrezime.setText("Prezime laboranta:*");

        lblBrojDosijea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBrojDosijea.setText("Broj dosijea:*");

        lblBrojOrdinacije.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBrojOrdinacije.setText("Broj ordinacije:*");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Test za koji je ovlašćen da izvodi:");

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtBrojDosijea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBrojDosijea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojDosijeaActionPerformed(evt);
            }
        });

        txtBrojOrdinacije.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbTest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvajLaboranta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacuvajLaboranta.setText("Sačuvaj");
        btnSacuvajLaboranta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajLaborantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLaborantLayout = new javax.swing.GroupLayout(pnlLaborant);
        pnlLaborant.setLayout(pnlLaborantLayout);
        pnlLaborantLayout.setHorizontalGroup(
            pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLaborantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvajLaboranta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLaborantLayout.createSequentialGroup()
                        .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBrojDosijea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrojDosijea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLaborantLayout.createSequentialGroup()
                        .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLaborantLayout.createSequentialGroup()
                                .addComponent(lblBrojOrdinacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(154, 154, 154))
                            .addGroup(pnlLaborantLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBrojOrdinacije)
                            .addComponent(cbTest, 0, 326, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlLaborantLayout.setVerticalGroup(
            pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaborantLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojDosijea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrojDosijea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojOrdinacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrojOrdinacije, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLaborantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajLaboranta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLaborant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLaborant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrojDosijeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojDosijeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojDosijeaActionPerformed

    private void btnSacuvajLaborantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajLaborantaActionPerformed
        try {
            if (txtPrezime.getText().isEmpty() || txtBrojDosijea.getText().isEmpty() || txtBrojOrdinacije.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja označena sa *.");
                return;
            }
            String ime = txtIme.getText().trim();
            String prezime = txtPrezime.getText().trim();
            String dosije = txtBrojDosijea.getText().trim();
            double ordinacija = Double.parseDouble(txtBrojOrdinacije.getText().trim());
            if(ordinacija < 0){
                lblError.setForeground(Color.red);
                lblError.setText("Broj ordinacije mora biti veci od 0.");
                return;
            }
            Test test = (Test) cbTest.getSelectedItem();
            if (mod == ModForme.UNOS) {
                Laborant la = new Laborant(1l, ime, prezime, dosije, ordinacija, test);
                Kontroler.getInstance().sacuvajLaboranta(la);
                lblError.setText("");
                int option = JOptionPane.showConfirmDialog(this, "Laborant je uspesno sacuvan! Da li želite da nastavite unos?", "", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION){
                    txtIme.setText("");
                    txtPrezime.setText("");
                    txtBrojDosijea.setText("");
                    txtBrojOrdinacije.setText("");
                }else{
                    this.dispose();
                }
                return;
            }
            if (mod == ModForme.IZMENA) {
                Laborant pre = (Laborant) session.Session.getInstance().getUseCaseParams().get("izabraniLaborant");

                Laborant la = new Laborant(pre.getLaborantID(), ime, prezime, dosije, ordinacija, test);
                Kontroler.getInstance().azurirajLaboranta(la);
                lblError.setText("");
                JOptionPane.showMessageDialog(this, "Podaci o zadatom laborantu su izmenjeni.");
                PretragaForma parent = (PretragaForma) getParent();
                parent.osveziTabelu();
            }

        } catch (Exception ex) {
            Logger.getLogger(LaborantForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajLaborantaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajLaboranta;
    private javax.swing.JComboBox<Object> cbTest;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBrojDosijea;
    private javax.swing.JLabel lblBrojOrdinacije;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JPanel pnlLaborant;
    private javax.swing.JTextField txtBrojDosijea;
    private javax.swing.JTextField txtBrojOrdinacije;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void napuniKomboTestova() {
        cbTest.removeAllItems();
        try {
            List<Test> list = Kontroler.getInstance().dajSveTestove();
            for (Test test : list) {
                cbTest.addItem(test);
            }
        } catch (Exception ex) {
            Logger.getLogger(RezultatForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediFormu(ModForme mod) {
        switch (mod) {
            case UNOS:
                txtIme.setEnabled(true);
                txtPrezime.setEnabled(true);
                txtBrojDosijea.setEnabled(true);
                txtBrojOrdinacije.setEnabled(true);
                cbTest.setEnabled(true);
                btnSacuvajLaboranta.setVisible(true);
                setTitle("Dodavanje novog laboranta");
                break;
            case IZMENA:
                for (Object k : session.Session.getInstance().getUseCaseParams().keySet()) {
                    System.out.println(k);
                }
                Laborant l = (Laborant) session.Session.getInstance().getUseCaseParams().get("izabraniLaborant");
                txtIme.setEnabled(true);
                txtPrezime.setEnabled(true);
                txtBrojDosijea.setEnabled(true);
                txtBrojOrdinacije.setEnabled(true);
                cbTest.setEnabled(true);
                btnSacuvajLaboranta.setVisible(true);
                setTitle("Izmena laboranta");
                txtIme.setText(l.getIme());
                txtPrezime.setText(l.getPrezime());
                txtBrojDosijea.setText(l.getBrojDosijea());
                txtBrojOrdinacije.setText(l.getBrojOrdinacije() + "");
                cbTest.setEditable(true);
                cbTest.setSelectedItem(l.getTest());
                cbTest.setEditable(false);
                break;
            case PRIKAZ:
                txtIme.setEnabled(false);
                txtPrezime.setEnabled(false);
                txtBrojDosijea.setEnabled(false);
                txtBrojOrdinacije.setEnabled(false);
                cbTest.setEnabled(false);
                btnSacuvajLaboranta.setVisible(false);
                setTitle("Prikaz laboranta");

                break;
        }
    }
}
