/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.test;

import kontroler.Kontroler;
import domen.Vrsta;
import domen.TerminTestiranja;
import domen.Test;
import gui.termin.RezultatForma;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Milica
 */
public class TestForma extends javax.swing.JDialog {

    /**
     * Creates new form FrmTest
     */
    public TestForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        napuniKomboVrsta();
        setTitle("Dodavanje novog testa");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        lblUputstvoZaPrimenu = new javax.swing.JLabel();
        lblVrsta = new javax.swing.JLabel();
        lblOznaka = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtOpis = new javax.swing.JTextField();
        txtUputstvoZaPrimenu = new javax.swing.JTextField();
        cbVrsta = new javax.swing.JComboBox<>();
        txtOznaka = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unesite podatke o testu  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNaziv.setText("Naziv testa:*");

        lblOpis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOpis.setText("Opis:*");

        lblUputstvoZaPrimenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUputstvoZaPrimenu.setText("Uputstvo za primenu:*");

        lblVrsta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVrsta.setText("Vrsta testa:*");

        lblOznaka.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOznaka.setText("Oznaka:");

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtOpis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUputstvoZaPrimenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbVrsta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbVrsta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtOznaka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSacuvaj.setBackground(new java.awt.Color(204, 204, 204));
        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacuvaj.setText("Sačuvaj novi test");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVrsta)
                            .addComponent(lblUputstvoZaPrimenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(txtOpis)
                            .addComponent(txtUputstvoZaPrimenu)
                            .addComponent(txtOznaka)
                            .addComponent(cbVrsta, 0, 319, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUputstvoZaPrimenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUputstvoZaPrimenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            if(txtNaziv.getText().isEmpty() || txtOpis.getText().isEmpty() || txtUputstvoZaPrimenu.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja oznacena sa *");
                return;
            }
            String naziv = txtNaziv.getText().trim();
            String opis = txtOpis.getText().trim();
            String uputstvoZaPrimenu = txtUputstvoZaPrimenu.getText().trim();
            String vrstaString = (String) cbVrsta.getSelectedItem();
            Vrsta vrsta = Vrsta.valueOf(vrstaString);
            String oznaka = txtOznaka.getText().trim();
            
            Test test = new Test(Long.MIN_VALUE, naziv, opis, uputstvoZaPrimenu, vrsta, oznaka);
            Kontroler.getInstance().sacuvajTest(test);
            int option = JOptionPane.showConfirmDialog(this, "Test je uspesno sacuvan. Da li zelite da unesete jos neki test?","",JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                txtNaziv.setText("");
                txtOpis.setText("");
                txtUputstvoZaPrimenu.setText("");
                txtOznaka.setText("");
            }else{
                this.dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(TestForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cbVrsta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblOznaka;
    private javax.swing.JLabel lblUputstvoZaPrimenu;
    private javax.swing.JLabel lblVrsta;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JTextField txtUputstvoZaPrimenu;
    // End of variables declaration//GEN-END:variables

    private void napuniKomboVrsta() {
        cbVrsta.removeAllItems();
        try {
            for (Vrsta v : Vrsta.values()) {
                cbVrsta.addItem(v.toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(RezultatForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
