/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import kontroler.Kontroler;
import java.awt.Color;
 import java.awt.Graphics;  
 import java.awt.Image;  
 import java.awt.Toolkit;  
 import javax.swing.JPanel; 

/**
 *
 * @author Milica
 */
public class ServerForma extends javax.swing.JFrame {

    /**
     * Creates new form FrmServer
     */
    public ServerForma() {
        initComponents();
        setLocationRelativeTo(null);
        adjustForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        lblStatus = new javax.swing.JLabel();
        btnStopServer = new javax.swing.JButton();
        btnStartServer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPodesavanja = new javax.swing.JMenu();
        jmiChangeDatabaseParameters = new javax.swing.JMenuItem();
        jmiAddUser = new javax.swing.JMenuItem();
        jmiDeleteUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setForeground(new java.awt.Color(255, 0, 0));

        lblStatus.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblStatus.setText("Status servera:");

        btnStopServer.setBackground(new java.awt.Color(255, 255, 255));
        btnStopServer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStopServer.setText("Zaustavi server");
        btnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopServerActionPerformed(evt);
            }
        });

        btnStartServer.setBackground(new java.awt.Color(255, 255, 255));
        btnStartServer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStartServer.setText("Pokreni server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Covid-19-Intelligence-Service-logo-RENEE-FINAL-300x110.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmPodesavanja.setBackground(new java.awt.Color(0, 51, 255));
        jmPodesavanja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jmPodesavanja.setForeground(new java.awt.Color(204, 0, 0));
        jmPodesavanja.setText("Podešavanja");
        jmPodesavanja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmPodesavanja.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N

        jmiChangeDatabaseParameters.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiChangeDatabaseParameters.setText("Izmena parametara za konekciju na bazu podataka");
        jmiChangeDatabaseParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChangeDatabaseParametersActionPerformed(evt);
            }
        });
        jmPodesavanja.add(jmiChangeDatabaseParameters);

        jmiAddUser.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiAddUser.setText("Dodavanje administratora");
        jmiAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddUserActionPerformed(evt);
            }
        });
        jmPodesavanja.add(jmiAddUser);

        jmiDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiDeleteUser.setText("Brisanje administratora");
        jmiDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeleteUserActionPerformed(evt);
            }
        });
        jmPodesavanja.add(jmiDeleteUser);

        jMenuBar1.add(jmPodesavanja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblStatus)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddUserActionPerformed
        new DodajAdministratoraForma(this, true).setVisible(true);
    }//GEN-LAST:event_jmiAddUserActionPerformed

    private void jmiChangeDatabaseParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChangeDatabaseParametersActionPerformed
        new IzmeniParametreForma(this, true).setVisible(true);
    }//GEN-LAST:event_jmiChangeDatabaseParametersActionPerformed

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        Kontroler.getInstance().startServer();
        btnStartServer.setEnabled(false);
        btnStopServer.setEnabled(true);
        lblStatus.setForeground(Color.green);
        lblStatus.setText("Server je pokrenut");
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopServerActionPerformed
        Kontroler.getInstance().stopServer();
        btnStartServer.setEnabled(true);
        btnStopServer.setEnabled(false);
        lblStatus.setForeground(Color.red);
        lblStatus.setText("Server je zaustavljen");
    }//GEN-LAST:event_btnStopServerActionPerformed

    private void jmiDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeleteUserActionPerformed
        new ObrisiAdministratoraForma(this, true).setVisible(true);
    }//GEN-LAST:event_jmiDeleteUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu jmPodesavanja;
    private javax.swing.JMenuItem jmiAddUser;
    private javax.swing.JMenuItem jmiChangeDatabaseParameters;
    private javax.swing.JMenuItem jmiDeleteUser;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    private void adjustForm() {
        lblStatus.setForeground(Color.red);
        lblStatus.setText("Server nije pokrenut");
        btnStartServer.setEnabled(true);
        btnStopServer.setEnabled(false);
        setTitle("Server");
    }
}
